# This is a basic workflow to help you get started with Actions

name: CI  
run-name: ${{ github.actor }} is learning GitHub Actions 

on:

  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest  
  
    environment: test
    concurrency: test

    steps:
      - name: test
        shell: powershell
        run: ./deployment.ps1
        

    
    
    
